name: fleet_pulse
description: "FleetPulse - Plataforma IoT para monitoreo inteligente de flotas vehiculares"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Routing
  go_router: ^14.6.2
  
  # HTTP Client
  dio: ^5.7.0
  
  # WebSocket
  web_socket_channel: ^3.0.1
  
  # Local Storage
  sqflite: ^2.4.1
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  
  # JSON
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # Maps
  google_maps_flutter: ^2.14.2
  google_maps_flutter_web: ^0.5.10
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  
  # Utils
  intl: ^0.20.1
  uuid: ^4.5.1
  logger: ^2.5.0
  signalr_netcore: ^1.4.4
  geolocator: ^14.0.3

  #charts
  syncfusion_flutter_charts: ^34.1.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.2
  json_serializable: ^6.9.2
  freezed: 2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - assets/icons/